/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package climatsimulat;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.*;
import javax.swing.JOptionPane;
import com.sun.speech.freetts.*;
import com.teknikindustries.yahooweather.WeatherDisplay;
import com.teknikindustries.yahooweather.WeatherDoc;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import java.net.*;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

/**
 *
 * @author Mehdi
 */
public class SVSCA extends javax.swing.JFrame {

    /**
     * Creates new form SVSCA
     */
     
    int manuelauto=0;
    int onoff=0;
    int timrun=0;
    int sec;
    public SVSCA() {
    initComponents();
     SetIcon();   
        new Thread()
        {
            
            public void run(){
                  
            while(timrun==0)
            {
                 
                Calendar cal=new GregorianCalendar();
                int hour=cal.get(Calendar.HOUR);
                  int min=cal.get(Calendar.MINUTE);
                      sec=cal.get(Calendar.SECOND);
                      int am_pm=cal.get(Calendar.AM_PM);
                 int month=cal.get(Calendar.MONTH);
                 int year=cal.get(Calendar.YEAR);
                 int day=cal.get(Calendar.DAY_OF_MONTH);
                 date.setText(day+"/"+(month+1)+"/"+year);
                      String day_night="";
                      if(am_pm==1)
                      {day_night="PM";}else{day_night="AM";}
                           String time=hour+":"+min+":"+sec+day_night;
                      Clook.setText(time);
                       
            }
        
           getWeather();   
             
            }
        }.start();
    }
   private void SetIcon()
   {
       setIconImage(Toolkit.getDefaultToolkit().getImage( getClass().getResource("SVSCA.png")));
   }
   String temperature;
    int vt;
      
   public static String scodev="1253867";
private void getWeather(){
     WeatherDoc  doc=new WeatherDoc(scodev,"c");
      WeatherDisplay disp=new WeatherDisplay();
      WeatherDisplay disp2=new WeatherDisplay();
         weather.setText(disp.getTemperature());
          
          temperature=disp.getTemperature();
            vt=(Integer.parseInt(temperature))+5;
           String conv=""+vt;
           voitureTem.setText(conv);
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        fonctionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        wiki = new javax.swing.JButton();
        coditionpanel = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        testerconnection = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        testeruppaal = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        foxit = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        verifpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        uppaal = new javax.swing.JButton();
        simulpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        weather = new javax.swing.JLabel();
        manual = new javax.swing.JButton();
        on = new javax.swing.JButton();
        off = new javax.swing.JButton();
        auto = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        voitureTem = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        down = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        Communication = new javax.swing.JLabel();
        Clook = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        fb = new javax.swing.JRadioButton();
        bb = new javax.swing.JRadioButton();
        ab = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        rapport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        villlesite = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        codetf = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        connec = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulateur d'un Verificateur des Systemes de Climatisation Automobile 1.0 2016");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        setSize(new java.awt.Dimension(822, 686));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\2.PNG")); // NOI18N
        jLabel2.setText(" ");

        jLabel4.setFont(new java.awt.Font("Andalus", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText(" Fonction de Climatiseur:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText(" La climatisation de véhicule automobile est un système qui permet de refroidir et assainir  l'habitacle");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText(" d'une automobile lorsque la température, ou l'humidité, extérieure est  supérieure à celle souhaitée ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText(" La climatisation est couplée avec un système de ventilation et de chauffage. ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText(" à l’intérieur. ");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\Capture.PNG")); // NOI18N
        jLabel8.setText(" ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("pour plus d'information appuyer sur le lien suivant: ");

        wiki.setBackground(new java.awt.Color(153, 153, 255));
        wiki.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wiki.setForeground(new java.awt.Color(0, 0, 153));
        wiki.setText("Click ici");
        wiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wikiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fpLayout = new javax.swing.GroupLayout(fp);
        fp.setLayout(fpLayout);
        fpLayout.setHorizontalGroup(
            fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpLayout.createSequentialGroup()
                .addGroup(fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fpLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(wiki))
                    .addGroup(fpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        fpLayout.setVerticalGroup(
            fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wiki))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(fp);

        javax.swing.GroupLayout fonctionPanelLayout = new javax.swing.GroupLayout(fonctionPanel);
        fonctionPanel.setLayout(fonctionPanelLayout);
        fonctionPanelLayout.setHorizontalGroup(
            fonctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fonctionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        fonctionPanelLayout.setVerticalGroup(
            fonctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("fonction", fonctionPanel);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setText("SVSCA est un application qui simule le travaille d'un verificateur des systemes de climatisation d'automobile .");

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel39.setText("pour la bon fonction de SVSCA il faut respecter les conditions suivants: ");

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("-connection a internet.");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("-instaler l'outil UPPAAL.");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("    tester la connection avec un seule click sur la button suivant:");

        testerconnection.setBackground(new java.awt.Color(204, 204, 255));
        testerconnection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        testerconnection.setForeground(new java.awt.Color(0, 153, 0));
        testerconnection.setText("Tester Connexion");
        testerconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testerconnectionActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel43.setText("verifier l'existence de l'outil UPPAAL");

        testeruppaal.setBackground(new java.awt.Color(204, 204, 255));
        testeruppaal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        testeruppaal.setForeground(new java.awt.Color(0, 204, 0));
        testeruppaal.setText("UPPAAL");
        testeruppaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testeruppaalActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("-installer foxit reader.");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("verifier l'existence de foxit reader");

        foxit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        foxit.setForeground(new java.awt.Color(0, 153, 0));
        foxit.setText("Foxit Reader");
        foxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foxitActionPerformed(evt);
            }
        });

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\1447045108_advancedsettings.png")); // NOI18N
        jLabel46.setText(" ");

        javax.swing.GroupLayout coditionpanelLayout = new javax.swing.GroupLayout(coditionpanel);
        coditionpanel.setLayout(coditionpanelLayout);
        coditionpanelLayout.setHorizontalGroup(
            coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coditionpanelLayout.createSequentialGroup()
                .addGroup(coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addGroup(coditionpanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel44)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jLabel42))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(coditionpanelLayout.createSequentialGroup()
                .addGroup(coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45))
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(foxit))
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(testeruppaal))
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43))
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(testerconnection)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        coditionpanelLayout.setVerticalGroup(
            coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coditionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coditionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coditionpanelLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(testerconnection)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(testeruppaal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45)
                        .addGap(27, 27, 27)
                        .addComponent(foxit))
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("condition", coditionpanel);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("UPPAAL:");

        jLabel11.setText("est un outil pour la modélisation, la validation et la ");

        jLabel12.setText(" pour les systemes qui peuvent Ítre modélisés par");

        jLabel13.setText("Autrement, UPPAAL est approprié pour les systémes  ");

        jLabel14.setText("qui peuvent Ítre modélisés sous la forme de processus");

        jLabel15.setText("non-déterministes avec une structure de controle finie");

        jLabel16.setText("et des horloges avec des valeurs réelles , communiquant  ");

        jLabel17.setText("par des canaux ou des structures de données partagées.");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\uppaalCapture.PNG")); // NOI18N
        jLabel18.setText(" ");

        jLabel19.setText("vérification des systémes temps réel.Il est approprié");

        jLabel20.setText(" des automates temporisés.");

        uppaal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        uppaal.setForeground(new java.awt.Color(0, 0, 255));
        uppaal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\3.png")); // NOI18N
        uppaal.setText("<html> <head> </head> <body> <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#FFD700\">U</FONT>    <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#008080\"> P</FONT>    <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#FF0000\"> P</FONT>    <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#0000FF\">A</FONT>    <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#800000\"> A</FONT>    <FONT FACE=\"Impact\" SIZE=\"7\" COLOR=\"#FF00FF\"> L</FONT>   </body> </html>");
        uppaal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppaalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uppaal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(490, 490, 490)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(uppaal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout verifpanelLayout = new javax.swing.GroupLayout(verifpanel);
        verifpanel.setLayout(verifpanelLayout);
        verifpanelLayout.setHorizontalGroup(
            verifpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        verifpanelLayout.setVerticalGroup(
            verifpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("verification", verifpanel);

        simulpanel.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 8));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("Current temperature:");

        weather.setFont(new java.awt.Font("Andalus", 3, 48)); // NOI18N
        weather.setForeground(new java.awt.Color(255, 0, 51));
        weather.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weather.setText(" ");

        manual.setBackground(new java.awt.Color(204, 204, 204));
        manual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manual.setForeground(new java.awt.Color(204, 0, 51));
        manual.setText("Manual");
        manual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manualMouseClicked(evt);
            }
        });
        manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualActionPerformed(evt);
            }
        });

        on.setBackground(new java.awt.Color(204, 204, 204));
        on.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        on.setForeground(new java.awt.Color(204, 0, 51));
        on.setText("On");
        on.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onMouseClicked(evt);
            }
        });
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        off.setBackground(new java.awt.Color(204, 204, 204));
        off.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        off.setForeground(new java.awt.Color(51, 255, 0));
        off.setText("Off");
        buttonGroup2.add(off);
        off.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                offMouseClicked(evt);
            }
        });
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        auto.setBackground(new java.awt.Color(204, 204, 204));
        auto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        auto.setForeground(new java.awt.Color(204, 0, 51));
        auto.setText("Auto ");
        auto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoMouseClicked(evt);
            }
        });
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("The internal temperature:");

        voitureTem.setFont(new java.awt.Font("Andalus", 3, 48)); // NOI18N
        voitureTem.setForeground(new java.awt.Color(255, 0, 51));
        voitureTem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voitureTem.setText(" ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("C");

        down.setBackground(new java.awt.Color(204, 204, 204));
        down.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        down.setForeground(new java.awt.Color(204, 0, 51));
        down.setText("-");
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("C");

        up.setBackground(new java.awt.Color(204, 204, 204));
        up.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        up.setForeground(new java.awt.Color(204, 0, 51));
        up.setText(" +");
        up.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        Communication.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Communication.setForeground(new java.awt.Color(255, 0, 0));
        Communication.setText(" ");

        Clook.setFont(new java.awt.Font("DS-Digital", 1, 24)); // NOI18N
        Clook.setForeground(new java.awt.Color(0, 153, 0));
        Clook.setText(" ");

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setForeground(new java.awt.Color(0, 153, 0));
        date.setText(" ");

        fb.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(fb);
        fb.setForeground(new java.awt.Color(204, 0, 51));
        fb.setText("Forward");
        fb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fbMouseClicked(evt);
            }
        });
        fb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbActionPerformed(evt);
            }
        });

        bb.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(bb);
        bb.setForeground(new java.awt.Color(204, 0, 51));
        bb.setText("Back");
        bb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbMouseClicked(evt);
            }
        });
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });

        ab.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(ab);
        ab.setForeground(new java.awt.Color(204, 0, 51));
        ab.setText("All");
        ab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abMouseClicked(evt);
            }
        });
        ab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 153));
        jLabel22.setText("    SVSCA");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("Place run air conditioner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(weather, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(auto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(fb)
                                    .addComponent(bb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(on)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(off)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voitureTem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ab)
                                .addGap(199, 199, 199))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Clook, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(157, 157, 157))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Communication, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clook)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(manual)
                        .addComponent(on)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(weather))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(auto)
                                            .addComponent(off))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27))
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                                .addComponent(ab)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Communication, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voitureTem, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(up)
                            .addComponent(down))))
                .addContainerGap())
        );

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\5.PNG")); // NOI18N
        jLabel24.setText(" ");

        jLabel47.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\8x8FT-Vintage-Dark-Color-Damask-Wall-Dim-font-b-Baroque-b-font-Pattern-Custom-Photography-Studio.jpg")); // NOI18N
        jLabel47.setText(" ");

        javax.swing.GroupLayout simulpanelLayout = new javax.swing.GroupLayout(simulpanel);
        simulpanel.setLayout(simulpanelLayout);
        simulpanelLayout.setHorizontalGroup(
            simulpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulpanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        simulpanelLayout.setVerticalGroup(
            simulpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulpanelLayout.createSequentialGroup()
                .addGroup(simulpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simulpanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("simulation", simulpanel);

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        jButton2.setText("uppaal");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        rapport.setText("Creer Rapport");
        rapport.setFocusable(false);
        rapport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rapport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapportActionPerformed(evt);
            }
        });
        jToolBar1.add(rapport);

        jButton1.setText("ouvrir Rapport");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\Yahoo-Weather-.jpg")); // NOI18N
        jLabel28.setText(" ");

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\1447046205_Flat_Bed-01.png")); // NOI18N
        jButton6.setText(" ");

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\1447047132_Flat_Bed-20.png")); // NOI18N
        jButton7.setText(" ");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 0));
        jLabel29.setText("    suiver nous:");

        jLabel30.setText(" SVSCA est par default donne");

        jLabel31.setText("  la temperature de la ville ");

        jLabel32.setText("de Constantine.pour d'autre ");

        jLabel33.setText("villes visiter le site suivant:");

        villlesite.setBackground(new java.awt.Color(255, 255, 102));
        villlesite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        villlesite.setForeground(new java.awt.Color(102, 0, 102));
        villlesite.setText("ville-site");
        villlesite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villlesiteActionPerformed(evt);
            }
        });

        jLabel34.setText("puis entrer le code de votre");

        jLabel35.setText("ville dans le champ suivant:");

        codetf.setForeground(new java.awt.Color(255, 51, 102));
        codetf.setText("tapper le code ici");
        codetf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                codetfMouseReleased(evt);
            }
        });

        jLabel36.setText("puis click sur le button ");

        jButton8.setBackground(new java.awt.Color(255, 153, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 0, 102));
        jButton8.setText("Entrer le code");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel37.setText("        Merci");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(villlesite, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(codetf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(villlesite)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Andalus", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" SVSCA");

        jMenu1.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("uppaal");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        connec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        connec.setText("connection");
        connec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecActionPerformed(evt);
            }
        });
        jMenu1.add(connec);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("SCI");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("about us");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText(" help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("help us");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wikiActionPerformed
        try{
            String URL="https://fr.wikipedia.org/wiki/Climatisation_de_v%C3%A9hicule_automobile";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        };
    }//GEN-LAST:event_wikiActionPerformed

    private void manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualActionPerformed
        // TODO add your handling code here:
        if(onoff==1){
        Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        bc='a';
        try
        {
            voice.speak( "Manual mode activated");
             Communication.setText("Manual mode activated");
        }catch(Exception e){}
        manuelauto=1;}
    }//GEN-LAST:event_manualActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        
          Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        try
        {
            voice.speak( "Air conditioner has been activated");
            Communication.setText("Air conditioner has been activated");
            
        }catch(Exception e){}
        onoff=1;
    }//GEN-LAST:event_onActionPerformed

    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        // TODO add your handling code here:
        if(onoff==1){
        Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        try
        {
            voice.speak( "  automatic mode activated");
             Communication.setText("Automatic mode activated");
        }catch(Exception e){}
        manuelauto=2;
      if(vt>27){
           
            vt=23;
             String conv=""+vt;
              voitureTem.setText(conv);  
        } 

}
    }//GEN-LAST:event_autoActionPerformed

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
     
          Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        if(onoff==1){
        try
        {
            voice.speak( "  deactivate air conditioner");
            Communication.setText("Deactivate Air Conditioner");
        }catch(Exception e){}
        manuelauto=0;
        onoff=0;}
    }//GEN-LAST:event_offActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
      if((manuelauto==1)&&(onoff==1)){
        vt=vt+1;
   String conv=""+vt;
    voitureTem.setText(conv);
  }else {Communication.setText("probleme");} 
    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
     if((manuelauto==1)&&(onoff==1)){
        vt=vt-1;
   String conv=""+vt;
    voitureTem.setText(conv);
  }else {Communication.setText("probleme");} 
    }//GEN-LAST:event_downActionPerformed

    private void uppaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppaalActionPerformed
       Runtime runtime = Runtime.getRuntime();
			 try {
				runtime.exec(new String[] { "C:\\Users\\Mehdi\\Desktop\\uppaal\\uppaal-new-version.exe", "C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\verification\\cliiiiim.xml" } );
			} catch (IOException e) {
			}
        
    }//GEN-LAST:event_uppaalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Runtime runtime = Runtime.getRuntime();
			 try {
				runtime.exec(new String[] { "C:\\Users\\Mehdi\\Desktop\\uppaal\\uppaal-new-version.exe", "C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\verification\\cliiiiim.xml" } );
			} catch (IOException e) {
			} 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbActionPerformed
     Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        if(onoff==1)
       {
          try
        {
            voice.speak( "forward");
            Communication.setText("forward");
            
        }catch(Exception e){ Communication.setText("error");} 
       }else{Communication.setText("error");}
    }//GEN-LAST:event_fbActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
          Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        if(onoff==1)
       {
          try
        {
            voice.speak( "Back");
            Communication.setText("Back");
            
        }catch(Exception e){ Communication.setText("error");} 
       }else{Communication.setText("error");}
    }//GEN-LAST:event_bbActionPerformed

    private void abActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abActionPerformed
        Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(VOICENAME);
        voice.allocate();
        if(onoff==1)
       {
          try
        {
            voice.speak( "all");
            Communication.setText("all");
            
        }catch(Exception e){ Communication.setText("error");} 
       }else{Communication.setText("error");} 
    }//GEN-LAST:event_abActionPerformed

    private void rapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapportActionPerformed
    try
    {
        Document document;
        document = new  Document()  ;
        PdfWriter.getInstance(  document, new FileOutputStream("report.pdf") );
         document.open();
         String da=date.toString();
         document.add( new Paragraph("             SVSCA")); 
         document.add( new Paragraph("rapport de:verification de systeme de climatisation"));
         document.add(new Paragraph(new Date().toString()));
          document.add(new Paragraph("----------------------------------------------------------------------"));
          document.add( new Paragraph("code de ville:"+scodev));
          document.add( new Paragraph("Current temperature:"+temperature));
          String z=""+vt;
          document.add( new Paragraph("The internal temperature:"+z));
          Image image=Image.getInstance("C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\pictures\\rap.png");
          document.add(image);
        document.close();
    }
    catch(Exception e)
    {}     
    }//GEN-LAST:event_rapportActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
   try{
            String URL="https://fr.wikipedia.org/wiki/Climatisation_de_v%C3%A9hicule_automobile";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        };
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      Runtime runtime = Runtime.getRuntime();
			 try {
				runtime.exec(new String[] { "C:\\Users\\Mehdi\\Desktop\\uppaal\\uppaal-new-version.exe", "C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\verification\\cliiiiim.xml" } );
			} catch (IOException e) {
			} 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       java.awt.EventQueue.invokeLater(new Runnable() {
             @Override
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Runtime runtime = Runtime.getRuntime();
			 try {
				runtime.exec(new String[] { "C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\Foxit Reader.exe","C:\\Users\\Mehdi\\Documents\\NetBeansProjects\\ClimatSimulat\\report.pdf" } );
			} catch (IOException e) {
			} 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void villlesiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villlesiteActionPerformed
 try{
            String URL="http://woeid.rosselliot.co.nz/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        };
    }//GEN-LAST:event_villlesiteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   scodev=codetf.getText();
   getWeather();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void codetfMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codetfMouseReleased
   codetf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codetf.setForeground(Color.black);
              codetf.setText("");}});
    }//GEN-LAST:event_codetfMouseReleased

    private void onMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMouseClicked
 on.setForeground(Color.green);
 off.setForeground(Color.red);
    }//GEN-LAST:event_onMouseClicked

    private void manualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manualMouseClicked
   manual.setForeground(Color.green);
   up.setForeground(Color.green);
   down.setForeground(Color.green);
    }//GEN-LAST:event_manualMouseClicked

    private void autoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoMouseClicked
         auto.setForeground(Color.green);
          manual.setForeground(Color.red);
        up.setForeground(Color.red);
         down.setForeground(Color.red);
    }//GEN-LAST:event_autoMouseClicked

    private void fbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbMouseClicked
     fb.setForeground(Color.green);
     bb.setForeground(Color.red);
     ab.setForeground(Color.red);
    }//GEN-LAST:event_fbMouseClicked

    private void bbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbMouseClicked
         bb.setForeground(Color.green);
     fb.setForeground(Color.red);
     ab.setForeground(Color.red);
    }//GEN-LAST:event_bbMouseClicked

    private void abMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abMouseClicked
         ab.setForeground(Color.green);
     bb.setForeground(Color.red);
     fb.setForeground(Color.red);
    }//GEN-LAST:event_abMouseClicked

    private void offMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offMouseClicked
           off.setForeground(Color.green);
     on.setForeground(Color.red);
     manual.setForeground(Color.red);
        auto.setForeground(Color.red);
           up.setForeground(Color.red);
             down.setForeground(Color.red);
        fb.setForeground(Color.red);
     bb.setForeground(Color.red);
     ab.setForeground(Color.red);
    }//GEN-LAST:event_offMouseClicked

    private void testerconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testerconnectionActionPerformed
     Socket sok=new Socket();
     InetSocketAddress addr;
        addr = new InetSocketAddress("www.google.com",80);
        try
{
    sok.connect(addr,3000);
    javax.swing.JOptionPane.showMessageDialog(null,"true" );
}
catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(null,"false" );}
finally
        {
            try
            {
                sok.close();
            }
            catch(Exception e)
            {}
        }       
    }//GEN-LAST:event_testerconnectionActionPerformed

    private void testeruppaalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testeruppaalActionPerformed
        try {
                Runtime.getRuntime().exec( "C:\\Users\\Mehdi\\Desktop\\uppaal\\uppaal-new-version.exe" );
            } catch ( IOException e ) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_testeruppaalActionPerformed

    private void connecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecActionPerformed
       Socket sok=new Socket();
     InetSocketAddress addr;
        addr = new InetSocketAddress("www.google.com",80);
        try
{
    sok.connect(addr,3000);
    javax.swing.JOptionPane.showMessageDialog(null,"true" );
}
catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(null,"false" );}
finally
        {
            try
            {
                sok.close();
            }
            catch(Exception e)
            {}
        }
    }//GEN-LAST:event_connecActionPerformed

    private void foxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foxitActionPerformed
 try {
                Runtime.getRuntime().exec( "C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\Foxit Reader.exe" );
            } catch ( IOException e ) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_foxitActionPerformed
private char bc='\0';private  static final String VOICENAME="kevin16";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVSCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVSCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVSCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVSCA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVSCA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clook;
    private javax.swing.JLabel Communication;
    private javax.swing.JRadioButton ab;
    private javax.swing.JButton auto;
    private javax.swing.JRadioButton bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField codetf;
    private javax.swing.JPanel coditionpanel;
    private javax.swing.JMenuItem connec;
    private javax.swing.JLabel date;
    private javax.swing.JButton down;
    private javax.swing.JRadioButton fb;
    private javax.swing.JPanel fonctionPanel;
    private javax.swing.JButton foxit;
    private javax.swing.JPanel fp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton manual;
    private javax.swing.JButton off;
    private javax.swing.JButton on;
    private javax.swing.JButton rapport;
    private javax.swing.JPanel simulpanel;
    private javax.swing.JButton testerconnection;
    private javax.swing.JButton testeruppaal;
    private javax.swing.JButton up;
    private javax.swing.JButton uppaal;
    private javax.swing.JPanel verifpanel;
    private javax.swing.JButton villlesite;
    private javax.swing.JLabel voitureTem;
    private javax.swing.JLabel weather;
    private javax.swing.JButton wiki;
    // End of variables declaration//GEN-END:variables
}
